### ISSUE TITLE
Collect user stories

### ISSUE THREAD

**Issue by klizhentas** [mailgun/vulcand#151]
If you are using Vulcand at any project, feel free to post your comment telling your story here, I would love to know how does it work for you. I'm going to post some user stories in Readme and blog.

Thanks,
Sasha

**Comment by schmitch** [comment]
As already told you, we at envisia.de use it as a general purpose proxy for customer website's (not that many yet). So we use vulcand as a general purpose proxy even if told so we shouldn't.
Still our experience had some issues at first, due to the early adoption I think. But as the time grew, everything is solved really greatful.
If we have a new customer we generate a new Docker Container and upload it to our AWS infrastructure and announce the new Host(s) and route them with vulcand.


One thing we still struggle with, but more due to our limited time are the issue's i posted in #54.
Custom error messages based on the response code. But we can solve this even when vulcand couldn't support it natively thanks to middlewares.

Also cbreakers are cool and we always see if some backends failed after an automatic update of coreos.

Currently we also have an project which has a lot of API servers and we will use vulcand to route / glue everything together as soon the project goes live.

Thanks for the great work!

**Comment by klizhentas** [comment]
@schmitch Thanks a lot for your feedback and user story, I appreciate it! Regarding generic reverse proxy thing - it's mostly to highlight what my priorities are, I think your use case-makes sense for sure. I'm actually hosting vulcand docs using Vulcand myself :-)

**Comment by SEJeff** [comment]
Still not using it 'in production' yet, but have started building an internal PaaS powered by vulcand, mesos, and apache aurora for hosting a ton of internal webapps. I finalized on aurora after creating [this diagram](https://twitter.com/SEJeff/status/558489698319204352) since [docker support](https://reviews.apache.org/r/28920/) landed in Aurora master and will make it into 0.7.

**Comment by klizhentas** [comment]
@SEJeff Thanks a lot for sharing, let me know how it works for you when done!

**Comment by fracklen** [comment]
At [Lokalebasen.dk](http://www.lokalebasen.dk "lokalebasen.dk"), we started using it as of summer '14. 
At the time we used [kelseyhightower/confd](https://github.com/kelseyhightower/confd "confd") + nginx to get the same effect of using etcd as backend.
The old process was prone to a lot of errors, and often put nginx in a bad state.

Now we're using vulcand to host most of our apps in production. Our infrastructure still needs nginx + varnish in front of vulcand, so we're not using it as a general purpose proxy.

I'd say vulcand is awesome! It's an important piece of the puzzle in allowing us to do continuous deployment in a safe and reliable way. I'm looking forward to what a 1.0 release will bring!

**Comment by omegahm** [comment]
:+1: on the Lokalebasen.dk story

**Comment by SEJeff** [comment]
@fracklen Care to elaborate on why you chose nginx/varnish in front of vulcand? What does vulcand not provide that nginx/varnish does wrt reverse proxying?

**Comment by fracklen** [comment]
@SEJeff sure

Varnish is only there for caching. Although we have some special caching policies, where we want some content cached public, although a cookie will be sent from the client. I don't see why vulcand should bother with that. The VCL is very powerful for it's specific purpose.

Nginx currently routes traffic to our main application outside of vulcand. In there we need some special rules:

- Rewrites
- Paths to ignore (e. g. [/ali.txt](http://stackoverflow.com/questions/25274125/jsonparsererror-n-unexpected-token-at-alihackeval-request-alihack-c "alihack")
- Proxy header modifications 
- Custom error pages
- IP restrictions
- WebSockets support

I'm aware that some of these features have been implemented rather recently in vulcand. 

Apart from that, nginx does SSL-termination in our setup. Getting it to Qualys grade A was a walk in the park. From what I've seen in the pull-requests/issues, this has required quite a bit of work from @klizhentas. Before I have the time to test that the following works

- OCSP-Stapling
- Session resumption
- SPDY

I don't see vulcand replacing our SSL-termination any time soon.

We're only using vulcand as part of our service discovery. It does that very well!
> Write programs that do one thing and do it well. - Unix philosophy

**Comment by geowa4** [comment]
I'd like to see a way to have some kind of affinity for a particular server. I have a very simple cluster of 3 nodes with Vulcand (and etcd) on each. I also have the same 4 or 5 Docker containers running on each instance. I'd like a way for Vulcand to prefer the local instance of a service over the ones on other boxes. I could easily pass in the value of `hostname` as an argument to the Vulcand process.

**Comment by klizhentas** [comment]
@geowa4 Thanks for your feedback. I think this can be implemented by latency-based weighted load balancing algorithm. In case if latency difference are negligible, Vulcand will load balance round robin, in case if local servers are way better Vulcand can prefer the local servers. Let me know what do you think about it.

**Comment by geowa4** [comment]
@klizhentas that would be sufficient. Where would I find the docs on how to get that going?

**Comment by bmorton** [comment]
After experimenting with vulcand, CoreOS/Fleet, and Docker for a while, I decided to write some automation around zero-downtime deploys using vulcand to facilitate this.  The result of this is a project that I've been working on called [deployster](https://github.com/bmorton/deployster).

> Deployster uses a convention-over-configuration approach to simplify deploying Docker containers to a CoreOS Fleet cluster with zero downtime.

> It is implemented in Golang as an HTTP service exposing a REST API to automate interactions with Fleet, Docker, and Vulcand. As part of its convention-based approach, Deployster is opinionated in how images are tagged and stored, the configuration of unit files, and the bootstrapping of containers.

I've been developing it as openly as I can and I'm using it for some side-project stuff.  We're also experimenting with the idea at Yammer and its starting to get a small amount of attention from some other startups.

It mostly automates many of the processes that I've seen in tutorials and blog posts and it pretty much works thanks to vulcand.  Its not quite the same as the other user stories above, but I thought I'd mention it!  We're still using v0.7.0, but we've got support in the works for the v0.8.x branch as well.

**Comment by bmorton** [comment]
Oh, and if it wasn't clear, I love the project :)  It really is a joy to use and the amount of effort around documentation and making this easy to use is very appreciated.  Thank you.

(and :+1:  to the prefer-local-routing stuff mentioned above, that'd be cool to see :smile:)

**Comment by lucmichalski** [comment]
@klizhentas I think is absolutely cool, I will give a shot today, as I need to show to some people the potential, but only if somebody can help me to figure out something. :-) 

I just have a huge confusion about what would be the best ui to manage frontends, backends and middlewares with clarity for a quite important number of frontends, backends. 

I would have a couple of templates but would need to create some custom paths matching for the frontends, sometimes using http or tcp, and custom port mapping for backends.

Is Kubertenes, (Weave, Panamax) or any other solutions would help to visually understand the deployment graph ? Is there any docker container with a WEB UI available somewhere to create collections and search any data stored in etcd ?
